# Generated by Django 4.2.6 on 2024-02-16 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(max_length=1000)),
                ('imagen', models.ImageField(unique=True, upload_to='static/articulos')),
                ('creado', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Opiniones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valoracion', models.PositiveIntegerField()),
                ('nombre', models.CharField(max_length=50)),
                ('fecha', models.DateField()),
                ('comentario', models.TextField(max_length=1000)),
            ],
        ),
    ]
