# Generated by Django 4.2.6 on 2024-02-16 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psicoMRM', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='creado',
            field=models.DateField(auto_now=True),
        ),
    ]
