# Generated by Django 4.2.6 on 2024-02-16 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psicoMRM', '0002_alter_articulo_creado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='descripcion',
            field=models.TextField(max_length=7000),
        ),
    ]
