# Generated by Django 4.2.6 on 2024-01-25 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psicoMRM', '0003_alter_articulo_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='imagen',
            field=models.ImageField(unique=True, upload_to='static/articulos'),
        ),
    ]
